name: Retrieve Salesforce
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: webfactory/ssh-agent@v0.5.2     
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock       
        with:
          ref: refs/heads/master
          fetch-depth: 1
          ssh-private-key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}      
      - run: ssh-add - <<< "${{ secrets.GIT_SSH_PRIVATE_KEY }}"
      - run: git clone ${{ secrets.GIT_REPOSITORY_CONNECTION }}
      - run: cd ${{ secrets.GIT_REPOSITORY_FOLDER }}    
      - run: temp_branch=$(date +'%Y%m%d-%H%M%S%N')
      - run: git checkout -q -b $temp_branch      