name: Retrieve Salesforce
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup key
      uses: ./
      with:
          ssh-private-key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
    - run: |
        ssh-add -l
        echo SSH_AUTH_SOCK is at $SSH_AUTH_SOCK
        git clone ${{ secrets.GIT_REPOSITORY_CONNECTION }}    